#title in header
title: "Hi Bitcoin."

#main info
#owner
owner: "Johnny"
info: "Bitcoiner"
#description
desc: "World love bitcoin"

#menu
menu:
  Works: /Works
  About: /About

#index/main page max show posts (in number)
max_post: 8

# social profile at the footer/bottom
github: https://github.com/bitcoinjohnny
twitter: https://twitter.com/dreal
# js
nanobar: /js/nanobar.min.js

# favicon
favicon: /images/favicon.png

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: true
disqus_shortname: bitcoinjohnny
