#title in header
title: "Hi Bitcoin."

#main info
#owner
owner: "Bitcoin"
info: "is an innovative payment network and a new kind of money."
#description
desc: "If you don't believe me or don't get it,I don't have time to try to convince you,sorry.--Satoshi Nakamoto"

#menu
menu:
  What: /What/Bitcoin-Whitepaper-EN-CN.html
  About: /About/about.html

#index/main page max show posts (in number)
max_post: 10

# social profile at the footer/bottom
github: https://github.com/bitcoinjohnny
twitter: https://twitter.com/dreal
# js
nanobar: /js/nanobar.min.js

# favicon
favicon: /images/favicon.png

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: true
disqus_shortname: bitcoinjohnny
